apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
    - protocol: TCP
      port: 5153
      targetPort: 5153

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
        - name: coworking
          image: 286972227562.dkr.ecr.us-east-1.amazonaws.com/coworking:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5153

          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 5153
            initialDelaySeconds: 10
            timeoutSeconds: 5

          envFrom:
            - configMapRef:
                name: coworking-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coworking-secret
                  key: DB_PASSWORD